service: goes-notify-bot

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}



functions:
  post:
    handler: goes-notify-bot.lambda_handler
    events:
      - http:
          path: handler
          method: post
          cors: true